name: ARM64 lscpu

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run lscpu on ARM64
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker run --rm -t arm64v8/ubuntu lscpu
